version: '3'
services:
  students_tests_server:
    build: 
      context: ../
    container_name: students_tests_server
    ports:
      - 5000:5000
    env_file:
      - ./flask.env
      - ./postgres_db.env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15rc1-alpine3.16
    container_name: postgres_db
    ports:
      - 5432:5432
    env_file:
      - ./postgres_db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    