name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'

jobs:

  build:

    runs-on: ubuntu-20.04

    timeout-minutes: 20
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ykbhlvck/simon_tests_website
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-20.04

    timeout-minutes: 10
    permissions:
      contents: read
    steps:
    - name: Executing remote ssh docker deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP_ADDRESS }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        script: |
          cd /home/actions/docker-infra
          docker-compose pull students_tests_server && docker-compose up -d --build students_tests_server && docker system prune -f
